version: "3.4"

services:

  registry-serv:
    image: registry:2
    volumes:
      - $PWD/conf/registry-srv.yml:/etc/docker/registry/config.yml:ro
      - $PWD/conf/auth.cert:/etc/docker/registry/auth.cert:ro
      - $PWD/data:/var/lib/registry
    ports:
      - "5000:5000"
    networks:
      registry-net:
        ipv4_address: 172.19.0.2

  registry-web:
    image: hyper/docker-registry-web
    volumes:
      - $PWD/conf/registry-web.yml:/conf/config.yml:ro
      - $PWD/conf/auth.key:/conf/auth.key:ro
      - $PWD/db:/data
    ports:
      - "8080:8080"
    networks:
      registry-net:
        ipv4_address: 172.19.0.3

  my-nginx:
    image: nginx:latest
    volumes:
      - $PWD/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/conf/ssl:/etc/nginx/conf.d/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      registry-net:
        ipv4_address: 172.19.0.4


networks:
   registry-net:
      ipam:
         config:
         - subnet: 172.19.0.0/20
      driver: "bridge"
